# Makefile for Assignment 4
# Note: The CSV file (students.csv) is automatically generated by the program at runtime.
#       It is NOT required for compilation. The program creates it when you run ./student_erp

CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -g -pthread
AS = as

# Object files
OBJS = main.o StringUtils.o basicIO.o syscall.o

# Target executable
TARGET = student_erp

# Default target
all: $(TARGET)

# Link all object files
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS) -pthread

# Compile main.cpp
main.o: main.cpp Student.h StudentDatabase.h ParallelSort.h Iterator.h CSVReader.h basicIO.h StringUtils.h
	$(CXX) $(CXXFLAGS) -c main.cpp

# Compile StringUtils.cpp
StringUtils.o: StringUtils.cpp StringUtils.h
	$(CXX) $(CXXFLAGS) -c StringUtils.cpp

# Compile basicIO.cpp
basicIO.o: basicIO.cpp basicIO.h
	$(CXX) $(CXXFLAGS) -c basicIO.cpp

# Assemble syscall.S using GAS
syscall.o: syscall.s
	$(AS) syscall.s -o syscall.o

# Clean build artifacts only (not generated CSV files)
clean:
	rm -f $(OBJS) $(TARGET)

# Clean everything including generated data files
cleanall:
	rm -f $(OBJS) $(TARGET) students.csv *.csv

# Run the program (CSV will be auto-generated)
run: $(TARGET)
	./$(TARGET)

# Rebuild everything
rebuild: clean all

.PHONY: all clean cleanall run rebuild
